version: '3.7'

services:
  roamler_loc_api:
    container_name: roamler_loc_api
    build:
      context: .
      dockerfile: ./Roamler.API/Dockerfile
    environment:
      PUBLISHING_INTERVAL: 5s
      RoamlerGeoRedisDB: "roamler_loc_db:6379"
    ports:
      - "8040:80"
    restart: always
    healthcheck:
      test: curl --fail http://roamler_loc_api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      roamler_loc_db:
        condition: service_healthy
    
  roamler_loc_db:
    image: redis:alpine
    container_name: roamler_loc_db
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6380
        protocol: tcp
        mode: host
    volumes:
        - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 6

  roamler_test_db:
    image: redis:alpine
    container_name: roamler_test_db
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6381
        protocol: tcp
        mode: host
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 6
  
networks:
  stream_network:
    name: roamler_network
    external: true

volumes:
    redis_data:
