name: build-dot-net

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/      
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/      
    - name: Test
      run: dotnet test UnitTests --no-restore --verbosity normal
      working-directory: src/
